version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app-hot-reload
        ports:
            - '3000:3000'
        volumes:
            - ./src:/app/src
